"""Z6 T5D — weekly Stripe revenue digest.

Aggregates Stripe state via ``vendor_call``:

* ``retrieve_balance``  → available + pending totals.
* ``list_subscriptions`` (status=active) → active sub count, naive MRR
  (sum of unit_amount across active subscriptions where interval=month;
  yearly subs are normalised /12).

Writes ``mission_<id>/.stripe/digest_<YYYY-WW>.md`` and posts the
digest to the mission's Telegram thread when ``notify_user`` is wired.
File-only when no Telegram thread is available (system / cron path).

Cron registration: weekly internal cadence (604800s).
"""
from __future__ import annotations

import datetime
import json
import os
from typing import Any

from yazbunu import get_logger

logger = get_logger("mr_roboto.stripe_revenue_digest")

SYSTEM_MISSION_ID = 0


def _workspace_root() -> str:
    return os.environ.get("MISSION_WORKSPACE_ROOT", os.getcwd())


def _digest_path(workspace_root: str, mission_id: int, iso_year_week: str) -> str:
    return os.path.join(
        workspace_root, f"mission_{mission_id}", ".stripe",
        f"digest_{iso_year_week}.md",
    )


def _iso_year_week(now: datetime.datetime | None = None) -> str:
    now = now or datetime.datetime.utcnow()
    yr, wk, _ = now.isocalendar()
    return f"{yr}-W{wk:02d}"


# ── vendor_call indirection ────────────────────────────────────────────────


async def _vc(task: dict, service: str, action: str, params: dict) -> dict:
    from mr_roboto.executors.vendor_call import run as vendor_call_run
    sub = {
        "mission_id": task.get("mission_id"),
        "id": task.get("id"),
        "context": {
            "post_hook": {
                "service": service,
                "action": action,
                "params": params,
            }
        },
    }
    return await vendor_call_run(sub)


# ── compute helpers ────────────────────────────────────────────────────────


def _normalise_mrr(subscriptions: list[dict]) -> tuple[int, int, str]:
    """Return (active_count, mrr_cents, currency).

    Currency is the first observed sub's currency — naive but fine for v1.
    Yearly intervals are converted to monthly via /12; weekly/daily are
    multiplied to a monthly average. Custom intervals fall back to the
    raw unit_amount (one-shot interpretation).
    """
    active = [s for s in subscriptions if isinstance(s, dict)
              and s.get("status") == "active"]
    if not active:
        return 0, 0, "USD"
    currency = "USD"
    mrr_cents = 0
    for sub in active:
        items = (sub.get("items") or {}).get("data") or []
        for it in items:
            price = (it or {}).get("price") or {}
            ua = price.get("unit_amount") or 0
            cur = price.get("currency")
            if cur and currency == "USD":
                currency = str(cur).upper()
            recurring = price.get("recurring") or {}
            interval = recurring.get("interval", "month")
            count = recurring.get("interval_count", 1) or 1
            qty = it.get("quantity") or 1
            base = (ua or 0) * qty
            if interval == "month":
                mrr_cents += base // count
            elif interval == "year":
                mrr_cents += (base // count) // 12
            elif interval == "week":
                mrr_cents += int((base / count) * 4)
            elif interval == "day":
                mrr_cents += int((base / count) * 30)
            else:
                mrr_cents += base
    return len(active), int(mrr_cents), currency


def _format_money_cents(cents: int, currency: str) -> str:
    return f"{cents / 100:,.2f} {currency.upper()}"


def _render_digest(
    iso_yw: str,
    active_subs: int,
    mrr_cents: int,
    currency: str,
    balance_payload: dict,
) -> str:
    available = (balance_payload.get("available") or [{}])
    pending = (balance_payload.get("pending") or [{}])
    av = available[0] if available else {}
    pn = pending[0] if pending else {}
    mrr = _format_money_cents(mrr_cents, currency)
    arr = _format_money_cents(mrr_cents * 12, currency)
    return (
        f"# Stripe revenue digest — {iso_yw}\n\n"
        f"- Active subscriptions: **{active_subs}**\n"
        f"- MRR (naive): **{mrr}**\n"
        f"- ARR (12× MRR): **{arr}**\n"
        f"- Available balance: {_format_money_cents(int(av.get('amount') or 0), str(av.get('currency') or currency))}\n"
        f"- Pending balance: {_format_money_cents(int(pn.get('amount') or 0), str(pn.get('currency') or currency))}\n\n"
        "_Generated by stripe_revenue_digest (Z6 T5D). MRR is an "
        "approximation — yearly subs /12, weekly ×4, daily ×30._\n"
    )


# ── telegram surface (best-effort) ─────────────────────────────────────────


async def _post_to_mission_thread(mission_id: int, body: str) -> None:
    """Z6 polish P2 — surface the digest to Telegram (best-effort).

    Uses ``src.app.telegram_topics.post_to_mission_thread`` which already
    implements the same fallback the founder_action notifier uses:
    * If the mission has a ``telegram_thread_id``, send with
      ``message_thread_id=thread_id`` (forum topic).
    * If unset, fall back to flat-prefix ``[Mission {id}] ...`` to the
      admin chat.

    SYSTEM_MISSION_ID (cron path) → file-only, no Telegram send.
    """
    if mission_id == SYSTEM_MISSION_ID:
        return
    try:
        from src.app.telegram_bot import get_telegram
        from src.app.telegram_topics import post_to_mission_thread
    except Exception as exc:  # noqa: BLE001
        logger.debug("digest telegram imports deferred: %s", exc)
        return
    try:
        tg = get_telegram()
        if tg is None or getattr(tg, "app", None) is None:
            logger.debug("digest telegram: no interface available")
            return
        await post_to_mission_thread(tg.app.bot, mission_id, body)
    except Exception as exc:  # noqa: BLE001
        logger.debug("digest telegram post failed: %s", exc)


# ── main entrypoint ───────────────────────────────────────────────────────


async def run(task: dict[str, Any]) -> dict[str, Any]:
    mission_id = task.get("mission_id")
    if mission_id is None:
        mission_id_int = SYSTEM_MISSION_ID
    else:
        try:
            mission_id_int = int(mission_id)
        except (TypeError, ValueError):
            mission_id_int = SYSTEM_MISSION_ID

    bal_res = await _vc(task, "stripe", "retrieve_balance", {})
    if not bal_res.get("ok"):
        return {"ok": False, "reason": "retrieve_balance_failed", "detail": bal_res}
    balance_payload = bal_res.get("result") or {}

    sub_res = await _vc(
        task, "stripe", "list_subscriptions",
        {"status": "active", "limit": 100, "expand[]": "data.items.data.price"},
    )
    if not sub_res.get("ok"):
        return {"ok": False, "reason": "list_subscriptions_failed", "detail": sub_res}
    sub_payload = sub_res.get("result") or {}
    subs = sub_payload.get("data") if isinstance(sub_payload, dict) else []
    if not isinstance(subs, list):
        subs = []

    active_count, mrr_cents, currency = _normalise_mrr(subs)
    iso_yw = _iso_year_week()
    body = _render_digest(iso_yw, active_count, mrr_cents, currency, balance_payload)

    path = _digest_path(_workspace_root(), mission_id_int, iso_yw)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(body)

    await _post_to_mission_thread(mission_id_int, body)

    return {
        "ok": True,
        "iso_year_week": iso_yw,
        "active_subscriptions": active_count,
        "mrr_cents": mrr_cents,
        "currency": currency,
        "digest_path": path,
    }


__all__ = ["run"]
